# path: /
# appFile: notepad
# windowTitle: Notepad
hardwareKey: false # Some game using DirectX needs hardward key. Turn this flag on to receive the input
appName: RoadRash
pageTitle: "Cloud Morph Demo"
appMode: collaborative #app mode: collaborative/single (ex. collaborative: multiple user using same game session)
hasChat: true
path: /root/.wine/drive_c/Program Files (x86)/CGN/Road Rash/
appFile: ROADRASH.exe
windowTitle: Road
screenWidth: 640
screenHeight: 460
isWindowMode: false #app starts in window mode need to be rescaled to fullscreen, while app like game doesn't
