path: /
appFile: notepad
windowTitle: Notepad
hardwareKey: false #Direct X Input use different input set
appName: Notepad
pageTitle: "Cloud Morph Demo"
appMode: collaborative #app mode: collaborative/single (ex. collaborative: multiple user using same game session)
hasChat: true
# path: /apps/samurai
# appFile: SSVS.exe
# windowTitle: SAMURAI
# hardwareKey: true #Direct X Input use different input set
# appMode: collaborative #collaborative app mode (multiple user using same app session)

#path: /apps
#appFile: virtuacop2.exe
#windowTitle: VIRT
#path: /apps/Photoshop
#appFile: PhotoshopCS6Portable.exe
#windowTitle: Photoshop
