path: /
appFile: notepad
windowTitle: Notepad
hardwareKey: false #If it's Direct X game, turn this on as DX Input use different input set
appName: Notepad
pageTitle: "Cloud Morph Demo"
appMode: collaborative #app mode: collaborative/single (ex. collaborative: multiple user using same game session)
discoveryHost: http://178.128.125.200:7700
hasChat: true
