path: /apps/DiabloII
appFile: Game.exe
windowTitle: Diablo
hardwareKey: false
appName: Diablo
pageTitle: "Diablo - A Cloud Morph Demo"
appMode: collaborative
discoveryHost: http://discovery.cloudmorph.io:7700
hasChat: true
